### ISSUE TITLE
Terraform Provider Development program

### ISSUE THREAD

**Issue by cgriggs01** [strongdm/terraform-provider-sdm#10]
Hey Team,

Thanks for all the work you've put in to building this provider. There are a few items to address before we can release the provider and officially integrating it into Terraform. 

The website docs you have build look great but these are a few changes to get them ready to be published with the rest of the providers on Terraform.io. 
- [ ] Each provider has a ruby layout file that defines the sidebar directory for your providers docs. You can use the Random providers [random.erb](https://github.com/hashicorp/terraform-provider-random/blob/master/website/random.erb) as a reference.  Be aware that the the Random provider uses r/ and d/ for their directory names. 
- [ ] The files structure needs to be changed to follow our standard structure.
```
-website/
    -sdm.erb
    -docs
        -index.html
        -resources/ 
        -data-sources/
        -guides/
```
- [ ] Each markdown file should container the postfix `.html.md` or `.html.markdown` so that they can be sync with our middleman tool that builds the website. 
- [ ] There are two additional lines that need to be added to each documentation page. Layout and sidebar_current should align with the sdm.erb links. I.e. the following lines should be added to [account.md](https://github.com/strongdm/terraform-provider-sdm/blob/development/docs/resources/account.md).
```
layout: “sdm”
sidebar_current: “docs-sdm-resource-account”
```

- [ ] This GNUmakefile is standard across all Terraform providers, feel free to copy the [Random provider makefile](https://github.com/terraform-providers/terraform-provider-random/blob/master/GNUmakefile) and will just have to update the variable on line 4 to PKG_NAME=sdm

- [ ] There are four bash scripts kept in a scripts/ directory that are used in different processes of testing and release, these can all be copied from the [Random provider](https://github.com/terraform-providers/terraform-provider-random/tree/master/scripts)

- [ ] You are already using Go Modules to manage the providers dependancies which is great, but in addition to that, we require that all  dependancies are  checked into a `vendor/` directory.  This can be done by running `go mod vendor`.

- [ ] Each Terraform provider must have a CHANGELOG that is updated during reach release. Since the changeling is updated by a bot during the release it must be in a certain format. With the [AWS provider changelog](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md) as an example, the version of the next release should be tagged as “1.0.0 (Unreleased)” and will then be updated with a date by the release-bot. The version number is up to you but should follow semantic version practices.

- [ ] All providers have a TravisCI check with unit tests on each PR that is opened. Can you please add a .travis.yaml file to make the [standard configuration](https://github.com/terraform-providers/terraform-provider-null/blob/master/.travis.yml)

- [ ] One of our Terraform ecosystem engineers built a linter that helps align coding best practices for providers. You should use it along with your development. https://github.com/bflad/tfproviderlint

Once all these item are addressed we can start the final phase of the partner provider program which will be preformed by myself and another HashiCorp engineer.
- A repository under the same name `terraform-providers-sdm` will be created in the  [github.com/terraform-repositories/](http://github.com/terraform-repositories/)  organization. 
- Your provider code will be pushed up to the new repository
- Binaries will be built for  the following distributions and architectures.
`linux: 386; amd64; arm` 
`freebsd: 386; amd64; arm` 
`openbsd: 386; amd64`
`windows: amd64; 386`
`darwin: amd64`
`solaris: amd64`
- A `stable-website` branch will be created, this is where the  [terraform.io](http://terraform.io/)  provider documentation is source from. During each release, a bot will commit the changes in your master branch to the stable-website branch. If you need to make changes to the provider website docs in between releases, you can cherry-pick the commits to the stable-website branch. 
- The first release will be tagged as per your CHANGELOG.md
- You and whomever else on your team will be granted “write” access over the new repository are you are still seen as the owners and maintainers of the provider, before I grant you access, you’ll must review and agree to our community guidelines, which I’ll include below. 
- Whomever is added as a maintainer to the provider repository will also be granted an account on our #committers-terraform Slack channel, where you will request new versioned releases of the provider. 

Please let me know if you have any questions.

**Comment by britt** [comment]
Hey @cgriggs01, our team pushed an update today that should address all of the points in this issue. I will wait for your confirmation that everything is ready to go before closing it.
