### ISSUE TITLE
Docs seem to duplicate content/unclear as to which docs are correct

### ISSUE THREAD

**Issue by asachs01** [strongdm/terraform-provider-sdm#11]
Hi StrongDM team, 

I've been reviewing the docs and noticed that there are two sub directories which seem to duplicate content:

* Resources
* Data Sources

Additionally, given the content seems duplicated, it's unclear to me as to which set of docs are the canonical set of docs to follow for the provider, the "Resources" or "Data Sources" docs. FYI I had started down the path of attempting to fix the broken "Resources" link from the main pages site (looks like there's a `index.md` file missing in the "Resources" directory), which is what sent me down this rabbit hole 🙃

**Comment by sdm-keller** [comment]
Hi Aaron,

The directory structures of the SDM Terraform Provider repository conform to provider documentation publishing standards defined by HashiCorp.

For more information on these guidelines, as they apply to the resources and data-sources directories, see:   
https://www.terraform.io/docs/registry/providers/docs.html#format

If you would like some assistance working with our TF provider, please feel free to email strongDM customer support at support@strongdm.com and we'll be happy to assist.

Thanks Aaron!

Dan Keller
strongDM Support
