### ISSUE TITLE
Add support for encrypted aws_iam_access_key

### ISSUE THREAD

**Issue by nairb774** [strongdm/terraform-provider-sdm#14]
It would be nice to be able to use `aws_iam_access_key` with an `sdm_resource` without the secret key ending up unencrypted in the state file. The `aws_iam_access_key` resource supports a [`pgp_key`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_access_key#pgp_key) argument which can be used to encrypt the generated secret key. It would be nice if this could be used to prevent the secret key needing to end up in the state file. I understand that this likely will require changes beyond the terraform provider, but it would help a lot in being able to keep exposure to a minimum.

Would something like this be possible?

**Comment by Sebmono** [comment]
@nairb774 great news! We're currently in the process of adding support for AWS CLI commands through strongDM, which will allow you to use a `aws_iam_access_key` encrypted in strongDM to create resources, without storing any unencrypted secrets in the state file.

**Comment by 200sc** [comment]
Closing as resolved by the use of secret stores to prevent plaintext secrets from being exposed to the terraform state.
