### ISSUE TITLE
Please add website resources to provider

### ISSUE THREAD

**Issue by mazooz-chen** [strongdm/terraform-provider-sdm#16]

**Comment by wrenhunter** [comment]
Hi Chen

I'm happy to say that Websites are already part of the current strongDM Terraform provider:

https://registry.terraform.io/providers/strongdm/sdm/latest/docs/resources/resource

This page uses the actual types, so search for "http_basic" to see how the three different types are defined.

If you have any further questions on implementing this, please write to support@strongdm.com and we'll be glad to help!

Best,

David
