### ISSUE TITLE
v1.0.21+ fails to compile compile, complains about sdm.SSHCustomerKey

### ISSUE THREAD

**Issue by benconnito** [strongdm/terraform-provider-sdm#17]
```
# github.com/strongdm/terraform-provider-sdm/sdm
--
275 | pkg/mod/github.com/strongdm/terraform-provider-sdm@v1.0.22/sdm/data_source_resource.go:3932:9: undefined: sdm.SSHCustomerKey
276 | pkg/mod/github.com/strongdm/terraform-provider-sdm@v1.0.22/sdm/resource_resource.go:6937:12: undefined: sdm.SSHCustomerKey
277 | pkg/mod/github.com/strongdm/terraform-provider-sdm@v1.0.22/sdm/resource_resource.go:6939:11: undefined: sdm.SSHCustomerKey
278 | pkg/mod/github.com/strongdm/terraform-provider-sdm@v1.0.22/sdm/resource_resource.go:7987:8: undefined: sdm.SSHCustomerKey
279 | pkg/mod/github.com/strongdm/terraform-provider-sdm@v1.0.22/sdm/resource_resource.go:9151:8: undefined: sdm.SSHCustomerKey
```

**Comment by wrenhunter** [comment]
Hi @benconnito thanks for filing the issue. May I ask if you are a current strongDM client, or if you are running a trial with us? If so, please file a ticket by emailing support@strongdm.com. If not, I'll do my best to give you a hand here.

Either way, can you please include:

- More detail about how you are compiling the provider, including platform, etc.
- Was this working for you before 1.0.22?

Thanks,

David

**Comment by benconnito** [comment]
will file support ticket. it was compiling on 1.0.20. however .21 and .22 failed

**Comment by benconnito** [comment]
actually looks like `1.0.23` should fix it
