### ISSUE TITLE
SDM Gateway Token as Output to Terraform Gateway Module

### ISSUE THREAD

**Issue by barywhyte** [strongdm/terraform-provider-sdm#20]
Following from this implementation https://registry.terraform.io/providers/strongdm/sdm/latest/docs/guides/how_to_create_a_gateway.

I have a terraform module that bootstrap a virtual machine as strongDM gateway on google cloud. I am trying to automate the entire process with terraform by following the above link to output the token as input to Gateway module. This is generating a strange error that is very difficult to interpret. Now I don't know if I am doing something wrong with this simple code.

## main.tf
```
resource "sdm_node" "gateway_1" {
  gateway {
    name           = "${var.gateway_number}-1"
    listen_address = "1.1.1.1:${var.gateway_port}"
  }
}
```

## output.tf
```
output "gateway_1_token" {
  value = "${sdm_node.gateway_1[0].token}"
  sensitive = true
}
```

Here is the error from `terraform plan`
```
Error: Error loading modules: module strongdm_gateways: Error loading .terraform/modules/6437dd99385fd35cdf8bdb458b9f5139/output.tf: Error reading config for output gateway_1_token: parse error at 1:33: expected "}" but found "."
```
I expect that the `token` keyword should be making appropriate API call to strongDM to generate the token as it is not explicitly defined at the resource level in `main.tf`

The error message seems explanatory but appears totally unrelated to what I am trying to do here. Can some please help with interpretation of this error?

**Comment by grioghar** [comment]
Hi Seun,

We've generated a support ticket #3261 on your behalf where we can better assist you via our standard support channels.

I'll be closing this github issue and following up with you there. 

Thanks!

Greg Thomas-Baldwin
strongDM Support
