### ISSUE TITLE
Cluster resource certificate_authority not populated in SDM

### ISSUE THREAD

**Issue by stormsilver** [strongdm/terraform-provider-sdm#23]
When creating any variety of Kubernetes cluster, the value supplied for `certificate_authority` does not actually persist into SDM, leading to a cluster configuration that doesn't work.

* Example terraform project:
  https://gist.github.com/stormsilver/fd26def1b2b715a57b75501365264db6
  ```tf
    resource "sdm_resource" "cluster" {
      amazon_eks {
        ...
        certificate_authority = base64decode(aws_eks_cluster.cluster.certificate_authority.0.data)
        ...
      }
    }
  ```
* Results in this
  <img width="1379" alt="Screen Shot 2021-08-31 at 13 38 37" src="https://user-images.githubusercontent.com/135457/131558326-535bbb8b-c24a-43fd-bb61-1f90ad161c51.png">

**Comment by turner-strongdm** [comment]
Hi Eric,

I'll go ahead a create a ticket for you in our support system.
