### ISSUE TITLE
Missing platform: `darwin_arm64`

### ISSUE THREAD

**Issue by lra** [strongdm/terraform-provider-sdm#24]
When trying to install the provider on `darwin_arm64` (Apple M1 Pro) I get:
```
╷
│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/strongdm/sdm v1.0.31 does not have a package available for your current platform, darwin_arm64.
│ 
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this provider may have different platforms supported.
╵
```

**Comment by camposer** [comment]
Hi @lra,

Thanks for reaching out to support. There's an open FR for publishing an arm64 version. Meanwhile, you could use a workaround: install the darwin_amd64 version of the Terraform CLI rather than the darwin_arm64. By doing this, Rosetta will take care of the emulation, and the providers all work.

If you need further assistance please open a ticket with support by sending an email to `support at strongdm.com`

**Comment by lra** [comment]
An open FR?
Yes, I'm using rosetta, but it randomly crashes the terraform plugins =( This is not perfect. Having a native plugin would help.

**Comment by camposer** [comment]
Sorry @lra, I meant to say: Feature Request :-)

**Comment by camposer** [comment]
Hi @lra 

I just wanted to let you know that there's a darwin_arm64 version of our SDM Terraform provider since version 1.0.38.

You could update your TF config with the following:
```
terraform {
  required_providers {
    sdm = {
      source  = "strongdm/sdm"
      version = ">= 1.0.38"
    }
  }
}
```

My output:
```
$ uname -m
arm64
$ terraform init
Initializing the backend...

Initializing provider plugins...
- Reusing previous version of strongdm/sdm from the dependency lock file
- Using previously-installed strongdm/sdm v1.0.38

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```
