### ISSUE TITLE
Missing Import Examples

### ISSUE THREAD

**Issue by adamo57** [strongdm/terraform-provider-sdm#25]
Most Terraform providers provide an example command to import existing infrastructure into their code. If would be nice to have those commands readily available in the Terraform providers documentation, to avoid the need to dig in order to find out how to import a resource

**Comment by 200sc** [comment]
We offer these docs now:
 
https://github.com/strongdm/terraform-provider-sdm/blob/master/docs/resources/account.md#import

Please reopen if this is insufficent.
