### ISSUE TITLE
On change of load balancer, gateway update does not work

### ISSUE THREAD

**Issue by pguinard-public-com** [strongdm/terraform-provider-sdm#26]
When replacing a load balancer for a gateway

Terraform plan output

```
  # sdm_node.gateway must be replaced
+/- resource "sdm_node" "gateway" {
      ~ id = "n-3da34a9e62016d0f" -> (known after apply)

      ~ gateway {
          ~ listen_address = "REMOVED.elb.us-east-1.amazonaws.com:443" -> (known after apply) # forces replacement
            name           = "REMOVED-1"
          ~ token          = (sensitive value)
            # (1 unchanged attribute hidden)
        }
    }
```

Terraform error

```
│ Error: cannot create Node: could not create gateway: item already exists: already exists: REMOVED-1
│
│   with sdm_node.gateway,
│   on strongdm.tf line 94, in resource "sdm_node" "gateway":
│   94: resource "sdm_node" "gateway" {
```

**Comment by mdube667** [comment]
Hi,

Thank you for creating this issue. I'll be happy to help.

I'd like to open a ticket within the SDM support system for this problem.

Could you please provide your email please?

Thanks
-Matt

**Comment by pguinard-public-com** [comment]
This has been worked around locally for this has been identified already and is in progress with a different unique id. The function of replace in the terraform provider is what is not working.

**Comment by mdube667** [comment]
Hi Patrick,

Our policy is to handle these requests in Zendesk. Would that be ok with you? 

Can we use your email please?

Thanks
-Matt

**Comment by pguinard-public-com** [comment]
I've opened a support ticket to get this moved there and have closed this issue as a result.

**Comment by 200sc** [comment]
In the latest version of the terraform provider I'm not able to reproduce this. Please reopen or reconnect with support if preferred, if there's still any problems.
