### ISSUE TITLE
resource exhausted: Sorry! You've made too many requests, try again

### ISSUE THREAD

**Issue by lra** [strongdm/terraform-provider-sdm#30]
Hi,

We have a big users base in strongdm and need to regularly plan it (users, grants, resources) to make sure it's not out of date.

We are now hitting the API limit each time we want to plan. Support granted us 2x the limit so we can now plan again, but this is going to be problematic again as we ramp up more resources and users.

Support suggested us to use https://registry.terraform.io/providers/hashicorp/time/latest/docs/resources/sleep to time the requests, but as the doc states, it's supposed to be a workaround until the provider handles the rate limiting itself, and times retries based on the API telling it how to time its requets.

Can we get timed requests at the provider level to prevent plan/apply to fail on big setups?

**Comment by 200sc** [comment]
This feature has been present since v2.2.0 and can be disabled with the `SDM_RETRY_RATE_LIMITS` environment variable if needed. Please reopen this issue if anything else is still needed.

**Comment by lra** [comment]
FTR, I don't see anything in the doc about this, but per https://github.com/strongdm/terraform-provider-sdm/blob/224e51284d0024c1fc3509747cc928f0bcd46e42/sdm/provider.go#L39-L43 is seems to be:
```go
			"retry_rate_limit_errors": {
				Type:        schema.TypeBool,
				Optional:    true,
				DefaultFunc: schema.EnvDefaultFunc("SDM_RETRY_RATE_LIMITS", "true"),
				Description: "Whether experienced rate limits should cause the client to sleep instead of erroring out",
			},
```
So it's supposed to be enabled by default.

Works for me, we run latest (v3.5.4) and we don't seem to be experiencing this issue for a while now, thanks.
