### ISSUE TITLE
Import example for Secrets Store is incorrect

### ISSUE THREAD

**Issue by marysdm** [strongdm/terraform-provider-sdm#31]
This doc shows an example that is incorrect: 
https://registry.terraform.io/providers/strongdm/sdm/latest/docs/resources/secret_store#import

Incorrect:
`$ terraform import SecretStore.example se-12345678`

Should be:
`$ terraform import sdm_secret_store.example se-12345678`

**Comment by 200sc** [comment]
The linked documentation is fixed!
