### ISSUE TITLE
Tags option not working for some Data Source filters

### ISSUE THREAD

**Issue by marysdm** [strongdm/terraform-provider-sdm#33]
Within Data Sources "sdm_account", "sdm_node", "sdm_role", "sdm_secret_store" list "tags" as an available argument, how ever if you use tags in these, the following exception during `terraform plan`: 
`Error: Unsupported block type, Blocks of type "tags" are not expected here.`

I tested with TF Provider version 2.2.0

Docs:
https://registry.terraform.io/providers/strongdm/sdm/latest/docs/data-sources/account
https://registry.terraform.io/providers/strongdm/sdm/latest/docs/data-sources/node
https://registry.terraform.io/providers/strongdm/sdm/latest/docs/data-sources/role
https://registry.terraform.io/providers/strongdm/sdm/latest/docs/data-sources/secret_store

**Comment by 200sc** [comment]
This was resolved in v2.5.0, and has test coverage now!
