### ISSUE TITLE
add way to set default tags

### ISSUE THREAD

**Issue by jwhitcraft** [strongdm/terraform-provider-sdm#37]
We have a lot of terrraform modules that create SDM Resources for their service that they are creating and while copying and pasting the tags around easy enough, it could cause some drift if something is missed.

What I'm looking for is to have the sdm provider work like how the aws provider does where you can [define default tags](https://www.hashicorp.com/blog/default-tags-in-the-terraform-aws-provider), so it would look something like this:

```terraform
provider "aws" {
  region  = var.aws_region
  profile = "my-aws-profile"

  default_tags {
    tags = module.tags.tags_no_name
  }
}

provider "sdm" {
  default_tags {
    tags = module.tags.tags_no_name
  }
}
```

That ways  all created resources will have the same set of tags that we can then create dynamic roles for.

**Comment by wellthatsjames** [comment]
Hey Jon, I'm closing this ticket and moving it to Zendesk. You should get another email soon!

Thanks,

James
