### ISSUE TITLE
username is not imported for mongo db resources

### ISSUE THREAD

**Issue by neelrr1** [strongdm/terraform-provider-sdm#39]
I believe I have discovered a bug with the SDM Terraform provider. I am importing MongoDB replica set resources into Terraform (v0.13.7) as `sdm_resource` with `mongo_legacy_replicaset ` blocks.

Most of the fields from my SDM resource are imported correctly, but it seems like `username` **is not**. Using the Python SDM client I've verified that the resources I'm importing do indeed have a `username` set, but these are not reflected in the Terraform plan after importing them.

Wanted to get some clarification on whether this is a known issue, potential workarounds, and whether a fix is planned. Thanks!

**Comment by Calagar30** [comment]
Hi @neelrr1,

Thank you for the report. Can you please make sure to open a ticket with support@strongdm.com? While opening a ticket, can you please also provide the terraform code that you use see we can test it? 

Also, please provide the exact steps you take so we can recreate the issue. 

Thanks:
Adam

**Comment by 200sc** [comment]
Version 3.12.0 of the provider should address this in coordination with some changes released today. Please feel free to reopen the ticket if you still encounter any problems.
