### ISSUE TITLE
Terraform does not catch username and password changes done on the website

### ISSUE THREAD

**Issue by lra** [strongdm/terraform-provider-sdm#42]
Hi,

Once a `sdm_resource` is created, if the username or the password is changed on strongdm.com, terraform does not know about it.

Here's a reproducible example:
```tf
terraform {
  required_providers {
    sdm = {
      source  = "strongdm/sdm"
    }
  }
}


resource "sdm_resource" "test" {
    postgres {
        name = "postgres-test"
        hostname = "example.com"
        database = "my-db"
        username = "admin"
        password = "hunter2"
        port = 5432
        tags = {
            region = "us-west"
            env = "dev"
        }
    }
}
```
```
Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```
Now if I `terraform plan`, all good:
```
No changes. Your infrastructure matches the configuration.
```
The problem is if I change the username or the password on the website:
![Capture d’écran 2023-03-29 à 18 01 41](https://user-images.githubusercontent.com/122286/228598621-b4b3453d-295b-417f-8f94-d0a02d14d5d9.png)
If I plan, I still get no changes:
```
No changes. Your infrastructure matches the configuration.
```
While I should see terraform stating that a sensible value has changed.

This works if I change some other properties, like the hostname:
```
Terraform will perform the following actions:

  # sdm_resource.test will be updated in-place
  ~ resource "sdm_resource" "test" {
        id = "rs-35b6cbbd64245ffb"

      ~ postgres {
          ~ hostname          = "example.com2" -> "example.com"
            name              = "postgres-test"
            tags              = {
                "env"    = "dev"
                "region" = "us-west"
            }
            # (8 unchanged attributes hidden)
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

This is problematic because we use terraform to make sure the passwords on all our systems match, and this behavior means we can never be sure that what's in strongdm is the password we set initially. If someone in our team fixed a password in strongdm and in the database, we'll never know in terraform, and on the next apply we might overwrite the fixed password without knowing.

**Comment by lra** [comment]
> We could return to terraform a secure hash, checksum, or other signal that indicates a change has taken place;

I was thinking the same, this would work for us.

> or we could allow resources to be marked as not editable outside of some automation jobs or by some specific actors / api key pairs.

Not sure this works, as this would encourage ppl to use the same shared actor/keys to circumvent the issue.

> In the meantime, secret store credential paths -are- permitted to be sent to clients like terraform, so if you were to retrieve credentials from AWS or a Vault that should be reflected in the terraform plan.

Thanks for the pointer, is it something we can use now in production? https://www.strongdm.com/docs/admin/secret-stores/  It could solve our issue indeed. If you confirm this is a workable for production systems, we'll start evaluating this solution.

> Or a naming or tagging scheme could be adopted to suggest AdminUI users should not modify resources managed by terraform.

This would not be solid enough, nobody is supposed to change passwords by hand in StrongDM already, and it happened ;)

**Comment by 200sc** [comment]
Yes, secret stores are generally available today and have undergone extensive testing and use in production environments, with the obvious caveat that more recent integrations (e.g. Delinea / Cyberark) haven't had as much time in the wild.

**Comment by lra** [comment]
Ok, so I assume the message on https://registry.terraform.io/providers/strongdm/sdm/latest/docs/resources/secret_store is out of date:
![Capture d’écran 2023-03-29 à 20 57 13](https://user-images.githubusercontent.com/122286/228640288-d913201e-a9a3-4cce-a0a7-08ab4cd9c7a7.png)

Thanks, we'll evaluate this solution, closing this ticket, but feel free to add a comment if you decide to support hash/checksum solution.
