### ISSUE TITLE
Fix sdm_resource > google_gke > healthcheck_namespace so that it's not permanently diffed

### ISSUE THREAD

**Issue by cgetzen** [strongdm/terraform-provider-sdm#45]
<img width="393" alt="image" src="https://github.com/strongdm/terraform-provider-sdm/assets/5449704/cb323d19-1f64-4114-a51b-c11611c8f6b8">

This should be a computed attribute.

**Comment by 200sc** [comment]
Thanks for opening this issue; we're tracking resolving this by marking healthcheck namespace fields as optional+computed.

**Comment by kungfukennyg** [comment]
HI @cgetzen we've released `terraform-provider-sdm` version 5.2.2 which should address this issue. Feel free to reopen if you're still seeing an issue.
