### ISSUE TITLE
Add port_override to google_gke resource

### ISSUE THREAD

**Issue by cgetzen** [strongdm/terraform-provider-sdm#46]
google_gke_user_impersonation also does not currently have port_override.

**Comment by 200sc** [comment]
Thanks for the report; I've opened an internal ticket to address this. I'll watch the ticket and see if we don't disagree on turning this field from something we need to manually specify, to something that is on by default and has to be explicitly removed, to prevent this in the future.

**Comment by 200sc** [comment]
@cgetzen This should be resolved in the latest version (5.2.0); a corresponding control plane update was deployed just a bit ago as well to support this. Feel free to reopen if its not working.
