### ISSUE TITLE
The port_override attribute of a sdm_resource should be optional when disabled in SDM settings

### ISSUE THREAD

**Issue by JPLachance** [strongdm/terraform-provider-sdm#5]
Greetings,

I'm playing with this provider and with StrongDM settings. In the StrongDM settings panel, it is possible to disable the port override feature and allow SDM users to override ports.

![Screen Shot 2020-04-15 at 12 25 56 PM](https://user-images.githubusercontent.com/3448802/79362187-47450300-7f14-11ea-8a62-86686401cf25.png)

I think this provider should fetch the StrongDM settings and make the port_override attribute mandatory only when the setting says so.

Regards,
Jean-Philippe Lachance

**Comment by etodd** [comment]
Hi Jean-Philippe, thanks for the feedback. We're looking at this now!

**Comment by etodd** [comment]
We've released a new version in which the `port_override` attribute is a computed attribute. Please let us know how that works for your use case!

**Comment by etodd** [comment]
Feel free to open another issue if there's further problems around the `port_override` attribute!
