### ISSUE TITLE
auto_grant = true in sdm_workflow

### ISSUE THREAD

**Issue by gajula-manasa** [strongdm/terraform-provider-sdm#52]
the auto_grant is not working in sdm slack, it is creating the workflow with empty approver and while trying to request access it is throwing error.

**Comment by TheFellow** [comment]
Hi @gajula-manasa, using `auto_grant = true` is deprecated. I've added a ticket to update the sample to be correct; Thank you for pointing it out.

In the meantime what you're likely looking for is to setup an [Approval Workflow](https://github.com/strongdm/terraform-provider-sdm/blob/master/docs/resources/approval_workflow.md) with an `approval_mode` of `automatic`.
You can also check the [Help Center](https://help.strongdm.com/hc/en-us) for more information or feel free to reach out to support.
