### ISSUE TITLE
Passwords, secrets, keys and other sensitive values should be marked as Sensitive

### ISSUE THREAD

**Issue by JPLachance** [strongdm/terraform-provider-sdm#7]
Greetings,

Terraform has a nice feature that allows us to mask sensitive values in Terraform plan / apply. At the moment, this provider does not leverage that feature in the sdm_resource resource which leads us to plans that can leak sensitive values:
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # sdm_resource.bd_readonly will be updated in-place
  ~ resource "sdm_resource" "bd_readonly" {
        id = "rs-0c5b6edfc93d4a01"

      ~ mysql {
            database      = "bd"
            hostname      = "bd.random.us-east-1.rds.amazonaws.com"
            name          = "bd-readonly"
          + password      = "mySuperPassword"
            port          = 3306
            port_override = 10001
            username      = "app_sdm_ro"
        }
    }
```

Since Terraform is expected to run in a CI tool like Jenkins, we don't want people with access to that Jenkins instance to gain access to the database password in clear text.

The fix is simple. When [declaring the resource schema](https://github.com/strongdm/terraform-provider-sdm/blob/master/sdm/resource_resource.go#L1240), simply add `Sensitive: true` for each element of the schema that can be considered sensitive.

For example:
```
"password": {
    Type:        schema.TypeString,
    Required:    true,
    Description: "",
}
```
Should be:
```
"password": {
    Type:        schema.TypeString,
    Required:    true,
    Description: "",
    Sensitive:   true,
}
```

Do you want me to open a pull request with all the fixes?

Regards,
Jean-Philippe Lachance

**Comment by etodd** [comment]
Hi Jean-Philippe,

Thanks for the bug report! This was an oversight, we'll get right on it! No PR necessary. Thanks again.
