### ISSUE TITLE
Provider "sdm" not available for installation

### ISSUE THREAD

**Issue by PaulWBrassard** [strongdm/terraform-provider-sdm#9]
The result of `terraform init` was:
```
Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...

Provider "sdm" not available for installation.

A provider named "sdm" could not be found in the Terraform Registry.

This may result from mistyping the provider name, or the given provider may
be a third-party provider that cannot be installed automatically.

In the latter case, the plugin must be installed manually by locating and
downloading a suitable distribution package and placing the plugin's executable
file in the following directory:
    terraform.d/plugins/darwin_amd64

Terraform detects necessary plugins by inspecting the configuration and state.
To view the provider versions requested by each module, run
"terraform providers".


Error: no provider exists with the given name
```
It appears that doing a go build of this repo and placing it in ~/.terraform.d/plugins/darwin_amd64 (because I'm on a mac) solves this error. 
My request is two parts:
* Could this manual correction be documented please?
* Could this be added to the official Terraform providers so that it gets installed automatically?

**Comment by grioghar** [comment]
Hi Paul,

Concerning your request about updating the documentation: absolutely. I'll get that to the right person for update. 

Regarding the Terraform registration - We're still working on our partnership with HashiCorp. Once this is done, the strongDM provider should be added to the registry. 

Hopefully that helps. If you have further questions, don't hesitate to reach out here, or for a faster response, you can always contact Support at support@strongdm.com

**Comment by PaulWBrassard** [comment]
@magnua Why has this been marked as close without the update to the documentation?
